/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AddIntegrationToApplicationResponse } from '../models';
import { ApplicationIntegrationListByApplicationIdResponse } from '../models';
import { ApplicationintegrationAddintegrationtoapplicationBody } from '../models';
import { ApplicationintegrationAddintegrationtoapplicationBody1 } from '../models';
import { ApplicationintegrationAddintegrationtoapplicationBody2 } from '../models';
/**
 * ApplicationIntegrationApi - axios parameter creator
 * @export
 */
export const ApplicationIntegrationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * ### Error Codes | Code | Name | Message | | :--- | :--- | :--- | | 18_999_101 | ApplicationNotFound | Application not found. | | 18_999_102 | UnknownExceptionWhenCheckApplicationExistence | Unknown exception when checking if application exists. | | 18_999_103 | IntegrationNotFound | Integration not found. | | 18_999_104 | UnknownExceptionWhenCheckIntegrationExistence | Unknown exception when checking if integration exists. | | 18_999_105 | UnknownExceptionWhenAddIntegrationToApplication | Unknown exception when adding integration to application. | | 18_999_106 | IntegrationAlreadyAddedToTheApplication | You already map this integration to your application. | | 18_999_107 | UnknownExceptionWhenCheckApplicationIntegrationUniqueness |  |
         * @summary 18_999
         * @param {ApplicationintegrationAddintegrationtoapplicationBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        applicationIntegrationAddIntegrationToApplicationPost: async (body?: ApplicationintegrationAddintegrationtoapplicationBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/application-integration/add-integration-to-application`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * ### Error Codes | Code | Name | Message | | :--- | :--- | :--- | | 18_998 | UnknownExceptionWhenTryingFetchApplicationIntegrations |  | | 18_999 | ApplicationNotFound |  |
         * @summary 18_997
         * @param {string} [applicationId] 
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        applicationIntegrationApplicationIntegrationListByApplicationIdGet: async (applicationId?: string, page?: number, perPage?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/application-integration/application-integration-list-by-application-id`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (applicationId !== undefined) {
                localVarQueryParameter['ApplicationId'] = applicationId;
            }

            if (page !== undefined) {
                localVarQueryParameter['Page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['PerPage'] = perPage;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ApplicationIntegrationApi - functional programming interface
 * @export
 */
export const ApplicationIntegrationApiFp = function(configuration?: Configuration) {
    return {
        /**
         * ### Error Codes | Code | Name | Message | | :--- | :--- | :--- | | 18_999_101 | ApplicationNotFound | Application not found. | | 18_999_102 | UnknownExceptionWhenCheckApplicationExistence | Unknown exception when checking if application exists. | | 18_999_103 | IntegrationNotFound | Integration not found. | | 18_999_104 | UnknownExceptionWhenCheckIntegrationExistence | Unknown exception when checking if integration exists. | | 18_999_105 | UnknownExceptionWhenAddIntegrationToApplication | Unknown exception when adding integration to application. | | 18_999_106 | IntegrationAlreadyAddedToTheApplication | You already map this integration to your application. | | 18_999_107 | UnknownExceptionWhenCheckApplicationIntegrationUniqueness |  |
         * @summary 18_999
         * @param {ApplicationintegrationAddintegrationtoapplicationBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async applicationIntegrationAddIntegrationToApplicationPost(body?: ApplicationintegrationAddintegrationtoapplicationBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AddIntegrationToApplicationResponse>>> {
            const localVarAxiosArgs = await ApplicationIntegrationApiAxiosParamCreator(configuration).applicationIntegrationAddIntegrationToApplicationPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * ### Error Codes | Code | Name | Message | | :--- | :--- | :--- | | 18_998 | UnknownExceptionWhenTryingFetchApplicationIntegrations |  | | 18_999 | ApplicationNotFound |  |
         * @summary 18_997
         * @param {string} [applicationId] 
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async applicationIntegrationApplicationIntegrationListByApplicationIdGet(applicationId?: string, page?: number, perPage?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ApplicationIntegrationListByApplicationIdResponse>>> {
            const localVarAxiosArgs = await ApplicationIntegrationApiAxiosParamCreator(configuration).applicationIntegrationApplicationIntegrationListByApplicationIdGet(applicationId, page, perPage, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ApplicationIntegrationApi - factory interface
 * @export
 */
export const ApplicationIntegrationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * ### Error Codes | Code | Name | Message | | :--- | :--- | :--- | | 18_999_101 | ApplicationNotFound | Application not found. | | 18_999_102 | UnknownExceptionWhenCheckApplicationExistence | Unknown exception when checking if application exists. | | 18_999_103 | IntegrationNotFound | Integration not found. | | 18_999_104 | UnknownExceptionWhenCheckIntegrationExistence | Unknown exception when checking if integration exists. | | 18_999_105 | UnknownExceptionWhenAddIntegrationToApplication | Unknown exception when adding integration to application. | | 18_999_106 | IntegrationAlreadyAddedToTheApplication | You already map this integration to your application. | | 18_999_107 | UnknownExceptionWhenCheckApplicationIntegrationUniqueness |  |
         * @summary 18_999
         * @param {ApplicationintegrationAddintegrationtoapplicationBody} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async applicationIntegrationAddIntegrationToApplicationPost(body?: ApplicationintegrationAddintegrationtoapplicationBody, options?: AxiosRequestConfig): Promise<AxiosResponse<AddIntegrationToApplicationResponse>> {
            return ApplicationIntegrationApiFp(configuration).applicationIntegrationAddIntegrationToApplicationPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * ### Error Codes | Code | Name | Message | | :--- | :--- | :--- | | 18_998 | UnknownExceptionWhenTryingFetchApplicationIntegrations |  | | 18_999 | ApplicationNotFound |  |
         * @summary 18_997
         * @param {string} [applicationId] 
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async applicationIntegrationApplicationIntegrationListByApplicationIdGet(applicationId?: string, page?: number, perPage?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<ApplicationIntegrationListByApplicationIdResponse>> {
            return ApplicationIntegrationApiFp(configuration).applicationIntegrationApplicationIntegrationListByApplicationIdGet(applicationId, page, perPage, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ApplicationIntegrationApi - object-oriented interface
 * @export
 * @class ApplicationIntegrationApi
 * @extends {BaseAPI}
 */
export class ApplicationIntegrationApi extends BaseAPI {
    /**
     * ### Error Codes | Code | Name | Message | | :--- | :--- | :--- | | 18_999_101 | ApplicationNotFound | Application not found. | | 18_999_102 | UnknownExceptionWhenCheckApplicationExistence | Unknown exception when checking if application exists. | | 18_999_103 | IntegrationNotFound | Integration not found. | | 18_999_104 | UnknownExceptionWhenCheckIntegrationExistence | Unknown exception when checking if integration exists. | | 18_999_105 | UnknownExceptionWhenAddIntegrationToApplication | Unknown exception when adding integration to application. | | 18_999_106 | IntegrationAlreadyAddedToTheApplication | You already map this integration to your application. | | 18_999_107 | UnknownExceptionWhenCheckApplicationIntegrationUniqueness |  |
     * @summary 18_999
     * @param {ApplicationintegrationAddintegrationtoapplicationBody} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicationIntegrationApi
     */
    public async applicationIntegrationAddIntegrationToApplicationPost(body?: ApplicationintegrationAddintegrationtoapplicationBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<AddIntegrationToApplicationResponse>> {
        return ApplicationIntegrationApiFp(this.configuration).applicationIntegrationAddIntegrationToApplicationPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * ### Error Codes | Code | Name | Message | | :--- | :--- | :--- | | 18_998 | UnknownExceptionWhenTryingFetchApplicationIntegrations |  | | 18_999 | ApplicationNotFound |  |
     * @summary 18_997
     * @param {string} [applicationId] 
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicationIntegrationApi
     */
    public async applicationIntegrationApplicationIntegrationListByApplicationIdGet(applicationId?: string, page?: number, perPage?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<ApplicationIntegrationListByApplicationIdResponse>> {
        return ApplicationIntegrationApiFp(this.configuration).applicationIntegrationApplicationIntegrationListByApplicationIdGet(applicationId, page, perPage, options).then((request) => request(this.axios, this.basePath));
    }
}
