/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *   18999101 = ApplicationNotFound  18999102 = UnknownExceptionWhenCheckApplicationExistence  18999103 = IntegrationNotFound  18999104 = UnknownExceptionWhenCheckIntegrationExistence  18999105 = UnknownExceptionWhenAddIntegrationToApplication  18999106 = IntegrationAlreadyAddedToTheApplication  18999107 = UnknownExceptionWhenCheckApplicationIntegrationUniqueness
 * @export
 * @enum {string}
 */
export enum AddIntegrationToApplicationRequestErrorCodes {
    NUMBER_18999101 = 18999101,
    NUMBER_18999102 = 18999102,
    NUMBER_18999103 = 18999103,
    NUMBER_18999104 = 18999104,
    NUMBER_18999105 = 18999105,
    NUMBER_18999106 = 18999106,
    NUMBER_18999107 = 18999107
}

