/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AddIntegrationToApplicationError } from './add-integration-to-application-error';
 /**
 * 
 *
 * @export
 * @interface AddIntegrationToApplicationResponse
 */
export interface AddIntegrationToApplicationResponse {

    /**
     * @type {any}
     * @memberof AddIntegrationToApplicationResponse
     */
    data?: any | null;

    /**
     * @type {boolean}
     * @memberof AddIntegrationToApplicationResponse
     */
    success?: boolean;

    /**
     * @type {AddIntegrationToApplicationError}
     * @memberof AddIntegrationToApplicationResponse
     */
    error?: AddIntegrationToApplicationError | null;
}
