/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CreateApplicationApiKeyRequest } from './create-application-api-key-request';
import { CreateApplicationApiKeyRequestDto } from './create-application-api-key-request-dto';
 /**
 * 
 *
 * @export
 * @interface ApplicationapikeyGenerateBody1
 */
export interface ApplicationapikeyGenerateBody1 extends CreateApplicationApiKeyRequest {
}
