/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ApplicationApiKeyByApplicationIdError } from './application-api-key-by-application-id-error';
import { ApplicationApiKeyDto } from './application-api-key-dto';
 /**
 * 
 *
 * @export
 * @interface ApplicationApiKeyByApplicationIdResponse
 */
export interface ApplicationApiKeyByApplicationIdResponse {

    /**
     * @type {boolean}
     * @memberof ApplicationApiKeyByApplicationIdResponse
     */
    success?: boolean;

    /**
     * @type {ApplicationApiKeyDto}
     * @memberof ApplicationApiKeyByApplicationIdResponse
     */
    data?: ApplicationApiKeyDto | null;

    /**
     * @type {ApplicationApiKeyByApplicationIdError}
     * @memberof ApplicationApiKeyByApplicationIdResponse
     */
    error?: ApplicationApiKeyByApplicationIdError | null;
}
