/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ApplicationIntegrationListByApplicationIdError } from './application-integration-list-by-application-id-error';
import { ApplicationIntegrationListDto } from './application-integration-list-dto';
 /**
 * 
 *
 * @export
 * @interface ApplicationIntegrationListByApplicationIdResponse
 */
export interface ApplicationIntegrationListByApplicationIdResponse {

    /**
     * @type {boolean}
     * @memberof ApplicationIntegrationListByApplicationIdResponse
     */
    success?: boolean;

    /**
     * @type {ApplicationIntegrationListDto}
     * @memberof ApplicationIntegrationListByApplicationIdResponse
     */
    data?: ApplicationIntegrationListDto | null;

    /**
     * @type {ApplicationIntegrationListByApplicationIdError}
     * @memberof ApplicationIntegrationListByApplicationIdResponse
     */
    error?: ApplicationIntegrationListByApplicationIdError | null;
}
