/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *   16995101 = ApplicationApiKeyNotFound  16995102 = UnknownExceptionWhenTryingFetchApplications
 * @export
 * @enum {string}
 */
export enum ApplicationApiKeyByApplicationIdErrorCodes {
    NUMBER_16995101 = 16995101,
    NUMBER_16995102 = 16995102
}

