/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *   18998 = UnknownExceptionWhenTryingFetchApplicationIntegrations  18999 = ApplicationNotFound
 * @export
 * @enum {string}
 */
export enum ApplicationIntegrationListByApplicationIdRequestErrorCodes {
    NUMBER_18998 = 18998,
    NUMBER_18999 = 18999
}

