/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CallActionErrorCodes } from './call-action-error-codes';
import { ClientErrorType } from './client-error-type';
 /**
 * 
 *
 * @export
 * @interface CallActionError
 */
export interface CallActionError {

    /**
     * @type {CallActionErrorCodes}
     * @memberof CallActionError
     */
    code?: CallActionErrorCodes;

    /**
     *   1 = BusinessLogic  2 = InternalServerError
     *
     * @type {ClientErrorType}
     * @memberof CallActionError
     */
    type?: ClientErrorType;

    /**
     * @type {{ [key: string]: string; }}
     * @memberof CallActionError
     */
    values?: { [key: string]: string; } | null;
}
