/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CallActionDto } from './call-action-dto';
import { CallActionError } from './call-action-error';
 /**
 * 
 *
 * @export
 * @interface CallActionResponse
 */
export interface CallActionResponse {

    /**
     * @type {boolean}
     * @memberof CallActionResponse
     */
    success?: boolean;

    /**
     * @type {CallActionDto}
     * @memberof CallActionResponse
     */
    data?: CallActionDto | null;

    /**
     * @type {CallActionError}
     * @memberof CallActionResponse
     */
    error?: CallActionError | null;
}
