/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *   21997101 = TenantNotFound  21997102 = IntegrationNotFound  21997103 = UnknownExceptionWhenCallingThirdPartyApi  21997104 = UnknownExceptionWhenCallAction  21997105 = IntegrationIsNotEnabled
 * @export
 * @enum {string}
 */
export enum CallActionErrorCodes {
    NUMBER_21997101 = 21997101,
    NUMBER_21997102 = 21997102,
    NUMBER_21997103 = 21997103,
    NUMBER_21997104 = 21997104,
    NUMBER_21997105 = 21997105
}

