/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CategoryDto
 */
export interface CategoryDto {

    /**
     * @type {string}
     * @memberof CategoryDto
     */
    title?: string | null;

    /**
     * @type {boolean}
     * @memberof CategoryDto
     */
    isParent?: boolean;

    /**
     * @type {string}
     * @memberof CategoryDto
     */
    parentId?: string | null;

    /**
     * @type {string}
     * @memberof CategoryDto
     */
    id?: string;
}
