/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CategoryListDto } from './category-list-dto';
import { CategoryListError } from './category-list-error';
 /**
 * 
 *
 * @export
 * @interface CategoryListResponse
 */
export interface CategoryListResponse {

    /**
     * @type {boolean}
     * @memberof CategoryListResponse
     */
    success?: boolean;

    /**
     * @type {CategoryListDto}
     * @memberof CategoryListResponse
     */
    data?: CategoryListDto | null;

    /**
     * @type {CategoryListError}
     * @memberof CategoryListResponse
     */
    error?: CategoryListError | null;
}
