/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CreateUserProfileError } from './create-user-profile-error';
import { UserDto } from './user-dto';
 /**
 * 
 *
 * @export
 * @interface CreateUserProfileResponse
 */
export interface CreateUserProfileResponse {

    /**
     * @type {boolean}
     * @memberof CreateUserProfileResponse
     */
    success?: boolean;

    /**
     * @type {UserDto}
     * @memberof CreateUserProfileResponse
     */
    data?: UserDto | null;

    /**
     * @type {CreateUserProfileError}
     * @memberof CreateUserProfileResponse
     */
    error?: CreateUserProfileError | null;
}
