/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *   14998101 = UnknownExceptionWhenFetchJwtUserProfile  14998102 = UnknownExceptionWhenCreateUserProfile  14998103 = IncorrectDataInUserJwtPayload  14998104 = UnknownExceptionWhenSubscribeUserToFreePlan  14998105 = UserAlreadyExistInDataStorage  14998106 = UnknownExceptionWhenCheckUserExistence
 * @export
 * @enum {string}
 */
export enum CreateUserProfileRequestErrorCodes {
    NUMBER_14998101 = 14998101,
    NUMBER_14998102 = 14998102,
    NUMBER_14998103 = 14998103,
    NUMBER_14998104 = 14998104,
    NUMBER_14998105 = 14998105,
    NUMBER_14998106 = 14998106
}

