/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *   16999101 = ApplicationNotFound  16999102 = UnknownExceptionWhenCheckApplicationExistence  16999103 = UnknownExceptionWhenGenerateApplicationApiKey
 * @export
 * @enum {string}
 */
export enum CreateApplicationApiKeyRequestErrorCodes {
    NUMBER_16999101 = 16999101,
    NUMBER_16999102 = 16999102,
    NUMBER_16999103 = 16999103
}

