/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateApplicationApiKeyRequestDto
 */
export interface CreateApplicationApiKeyRequestDto {

    /**
     * @type {string}
     * @memberof CreateApplicationApiKeyRequestDto
     */
    webUrl?: string | null;

    /**
     * @type {Array<string>}
     * @memberof CreateApplicationApiKeyRequestDto
     */
    ipAddresses?: Array<string> | null;

    /**
     * @type {string}
     * @memberof CreateApplicationApiKeyRequestDto
     */
    applicationId?: string;
}
