/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CreateApplicationApiKeyRequestDto } from './create-application-api-key-request-dto';
 /**
 * 
 *
 * @export
 * @interface CreateApplicationApiKeyRequest
 */
export interface CreateApplicationApiKeyRequest {

    /**
     * @type {CreateApplicationApiKeyRequestDto}
     * @memberof CreateApplicationApiKeyRequest
     */
    dto?: CreateApplicationApiKeyRequestDto | null;
}
