/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ApplicationDto } from './application-dto';
import { CreateApplicationError } from './create-application-error';
 /**
 * 
 *
 * @export
 * @interface CreateApplicationResponse
 */
export interface CreateApplicationResponse {

    /**
     * @type {boolean}
     * @memberof CreateApplicationResponse
     */
    success?: boolean;

    /**
     * @type {ApplicationDto}
     * @memberof CreateApplicationResponse
     */
    data?: ApplicationDto | null;

    /**
     * @type {CreateApplicationError}
     * @memberof CreateApplicationResponse
     */
    error?: CreateApplicationError | null;
}
