/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ApplicationApiKeyDto } from './application-api-key-dto';
import { CreateApplicationApiKeyError } from './create-application-api-key-error';
 /**
 * 
 *
 * @export
 * @interface CreateApplicationApiKeyResponse
 */
export interface CreateApplicationApiKeyResponse {

    /**
     * @type {boolean}
     * @memberof CreateApplicationApiKeyResponse
     */
    success?: boolean;

    /**
     * @type {ApplicationApiKeyDto}
     * @memberof CreateApplicationApiKeyResponse
     */
    data?: ApplicationApiKeyDto | null;

    /**
     * @type {CreateApplicationApiKeyError}
     * @memberof CreateApplicationApiKeyResponse
     */
    error?: CreateApplicationApiKeyError | null;
}
