/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *   15999101 = ApplicationNameAlreadyExist  15999102 = UnknownExceptionWhenValidateApplicationNameUniqueness  15999103 = UnknownExceptionWhenInsertApplication  15999104 = UserNotFound  15999105 = UnknownExceptionWhenCreateOrganization
 * @export
 * @enum {string}
 */
export enum CreateApplicationRequestErrorCodes {
    NUMBER_15999101 = 15999101,
    NUMBER_15999102 = 15999102,
    NUMBER_15999103 = 15999103,
    NUMBER_15999104 = 15999104,
    NUMBER_15999105 = 15999105
}

