/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *   20996101 = TenantNotFound  20996102 = UnknownExceptionWhileFetchingTenant  20996103 = UnknownExceptionWhileDecliningTenant  20996104 = TenantIsNotInInvitedStatus  20996105 = UnknownExceptionWhileCheckingIfTenantIsInCorrectStatus
 * @export
 * @enum {string}
 */
export enum DeclineTenantInvitationRequestErrorCodes {
    NUMBER_20996101 = 20996101,
    NUMBER_20996102 = 20996102,
    NUMBER_20996103 = 20996103,
    NUMBER_20996104 = 20996104,
    NUMBER_20996105 = 20996105
}

