/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *   15997101 = ApplicationNotFound  15997102 = UnknownExceptionWhenFetchApplicationExistence  15997103 = UnknownExceptionWhenDeleteApplication
 * @export
 * @enum {string}
 */
export enum DeleteApplicationRequestErrorCodes {
    NUMBER_15997101 = 15997101,
    NUMBER_15997102 = 15997102,
    NUMBER_15997103 = 15997103
}

