/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetAuthenticationTokenDto
 */
export interface GetAuthenticationTokenDto {

    /**
     * @type {string}
     * @memberof GetAuthenticationTokenDto
     */
    accessToken?: string | null;

    /**
     * @type {string}
     * @memberof GetAuthenticationTokenDto
     */
    refreshToken?: string | null;

    /**
     * @type {number}
     * @memberof GetAuthenticationTokenDto
     */
    expiresIn?: number;
}
