/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *   23999101 = UnknownExceptionWhenTryingFetchApplicationApiKey  23999102 = FailedToFindApplicationApiKey  23999103 = UnknownExceptionWhenTryingToGetUserAuthenticationToken
 * @export
 * @enum {string}
 */
export enum GetAuthenticationTokenRequestErrorCodes {
    NUMBER_23999101 = 23999101,
    NUMBER_23999102 = 23999102,
    NUMBER_23999103 = 23999103
}

