/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GetOneIntegrationError } from './get-one-integration-error';
import { IntegrationDto } from './integration-dto';
 /**
 * 
 *
 * @export
 * @interface GetOneIntegrationResponse
 */
export interface GetOneIntegrationResponse {

    /**
     * @type {boolean}
     * @memberof GetOneIntegrationResponse
     */
    success?: boolean;

    /**
     * @type {IntegrationDto}
     * @memberof GetOneIntegrationResponse
     */
    data?: IntegrationDto | null;

    /**
     * @type {GetOneIntegrationError}
     * @memberof GetOneIntegrationResponse
     */
    error?: GetOneIntegrationError | null;
}
