/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GetAuthenticationTokenDto } from './get-authentication-token-dto';
import { GetAuthenticationTokenError } from './get-authentication-token-error';
 /**
 * 
 *
 * @export
 * @interface GetAuthenticationTokenResponse
 */
export interface GetAuthenticationTokenResponse {

    /**
     * @type {boolean}
     * @memberof GetAuthenticationTokenResponse
     */
    success?: boolean;

    /**
     * @type {GetAuthenticationTokenDto}
     * @memberof GetAuthenticationTokenResponse
     */
    data?: GetAuthenticationTokenDto | null;

    /**
     * @type {GetAuthenticationTokenError}
     * @memberof GetAuthenticationTokenResponse
     */
    error?: GetAuthenticationTokenError | null;
}
