/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { IntegrationEndpointDto } from './integration-endpoint-dto';
import { IntegrationEventDto } from './integration-event-dto';
import { ReleaseStatus } from './release-status';
 /**
 * 
 *
 * @export
 * @interface IntegrationDto
 */
export interface IntegrationDto {

    /**
     * @type {string}
     * @memberof IntegrationDto
     */
    id?: string;

    /**
     * @type {string}
     * @memberof IntegrationDto
     */
    title?: string | null;

    /**
     * @type {string}
     * @memberof IntegrationDto
     */
    nameIdentifier?: string | null;

    /**
     * @type {string}
     * @memberof IntegrationDto
     */
    shortDescription?: string | null;

    /**
     * @type {string}
     * @memberof IntegrationDto
     */
    icon?: string | null;

    /**
     *   0 = Released  1 = Pending  2 = NotPlanned
     *
     * @type {ReleaseStatus}
     * @memberof IntegrationDto
     */
    releaseStatus?: ReleaseStatus;

    /**
     * @type {Date}
     * @memberof IntegrationDto
     */
    launchDate?: Date | null;

    /**
     * @type {string}
     * @memberof IntegrationDto
     */
    documentationUrl?: string | null;

    /**
     * @type {string}
     * @memberof IntegrationDto
     */
    swaggerUrl?: string | null;

    /**
     * @type {Array<IntegrationEndpointDto>}
     * @memberof IntegrationDto
     */
    integrationEndpoints?: Array<IntegrationEndpointDto> | null;

    /**
     * @type {Array<IntegrationEventDto>}
     * @memberof IntegrationDto
     */
    integrationEvents?: Array<IntegrationEventDto> | null;
}
