/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { IntegrationDto } from './integration-dto';
 /**
 * 
 *
 * @export
 * @interface IntegrationListDto
 */
export interface IntegrationListDto {

    /**
     * @type {number}
     * @memberof IntegrationListDto
     */
    totalRecords: number;

    /**
     * @type {number}
     * @memberof IntegrationListDto
     */
    currentPage: number | null;

    /**
     * @type {number}
     * @memberof IntegrationListDto
     */
    perPage: number | null;

    /**
     * @type {Array<IntegrationDto>}
     * @memberof IntegrationListDto
     */
    items: Array<IntegrationDto> | null;
}
