/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface IntegrationFieldDto
 */
export interface IntegrationFieldDto {

    /**
     * @type {string}
     * @memberof IntegrationFieldDto
     */
    label?: string | null;

    /**
     * @type {boolean}
     * @memberof IntegrationFieldDto
     */
    required?: boolean;

    /**
     * @type {string}
     * @memberof IntegrationFieldDto
     */
    type?: string | null;
}
