/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { IntegrationFieldDto } from './integration-field-dto';
 /**
 * 
 *
 * @export
 * @interface IntegrationEventDto
 */
export interface IntegrationEventDto {

    /**
     * @type {string}
     * @memberof IntegrationEventDto
     */
    title?: string | null;

    /**
     * @type {string}
     * @memberof IntegrationEventDto
     */
    description?: string | null;

    /**
     * @type {Array<IntegrationFieldDto>}
     * @memberof IntegrationEventDto
     */
    fields?: Array<IntegrationFieldDto> | null;
}
