/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InviteTenantByApplicationIntegrationIdRequestDto } from './invite-tenant-by-application-integration-id-request-dto';
 /**
 * 
 *
 * @export
 * @interface InviteTenantByApplicationIntegrationIdRequest
 */
export interface InviteTenantByApplicationIntegrationIdRequest {

    /**
     * @type {InviteTenantByApplicationIntegrationIdRequestDto}
     * @memberof InviteTenantByApplicationIntegrationIdRequest
     */
    dto?: InviteTenantByApplicationIntegrationIdRequestDto | null;
}
