/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InviteTenantByApplicationIntegrationIdError } from './invite-tenant-by-application-integration-id-error';
import { TenantDto } from './tenant-dto';
 /**
 * 
 *
 * @export
 * @interface InviteTenantByApplicationIntegrationIdResponse
 */
export interface InviteTenantByApplicationIntegrationIdResponse {

    /**
     * @type {boolean}
     * @memberof InviteTenantByApplicationIntegrationIdResponse
     */
    success?: boolean;

    /**
     * @type {TenantDto}
     * @memberof InviteTenantByApplicationIntegrationIdResponse
     */
    data?: TenantDto | null;

    /**
     * @type {InviteTenantByApplicationIntegrationIdError}
     * @memberof InviteTenantByApplicationIntegrationIdResponse
     */
    error?: InviteTenantByApplicationIntegrationIdError | null;
}
