/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InviteTenantError } from './invite-tenant-error';
import { TenantDto } from './tenant-dto';
 /**
 * 
 *
 * @export
 * @interface InviteTenantResponse
 */
export interface InviteTenantResponse {

    /**
     * @type {boolean}
     * @memberof InviteTenantResponse
     */
    success?: boolean;

    /**
     * @type {TenantDto}
     * @memberof InviteTenantResponse
     */
    data?: TenantDto | null;

    /**
     * @type {InviteTenantError}
     * @memberof InviteTenantResponse
     */
    error?: InviteTenantError | null;
}
