/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *   20998101 = ApplicationIntegrationNotFound  20998102 = UnknownExceptionWhenCheckApplicationExistence  20998103 = UnknownExceptionWhenCreateTenant  20998104 = UnknownExceptionWhenSendingEmailToInvitedEmailAddress  20998105 = UserNotFound  20998106 = UnknownExceptionWhenInsertApplication  20998107 = UnknownExceptionWhenCreateUserTenant  20998108 = UnknownExceptionWhenCreatingEmailContent  20998109 = UnknownExceptionWhenCreatingEmailAcceptInvitationUrl  20998110 = UnknownExceptionWhenAddingTenantInKeycloak  20998111 = UnknownExceptionWhenAddingTenantInOrganization  20998112 = UnknownExceptionWhenCreateTenantUser
 * @export
 * @enum {string}
 */
export enum InviteTenantRequestErrorCodes {
    NUMBER_20998101 = 20998101,
    NUMBER_20998102 = 20998102,
    NUMBER_20998103 = 20998103,
    NUMBER_20998104 = 20998104,
    NUMBER_20998105 = 20998105,
    NUMBER_20998106 = 20998106,
    NUMBER_20998107 = 20998107,
    NUMBER_20998108 = 20998108,
    NUMBER_20998109 = 20998109,
    NUMBER_20998110 = 20998110,
    NUMBER_20998111 = 20998111,
    NUMBER_20998112 = 20998112
}

