/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OAuth2ChallengeTokenDto } from './oauth2-challenge-token-dto';
 /**
 * 
 *
 * @export
 * @interface OAuth2ChallengeDto
 */
export interface OAuth2ChallengeDto {

    /**
     * @type {string}
     * @memberof OAuth2ChallengeDto
     */
    redirectUrl?: string | null;

    /**
     * @type {OAuth2ChallengeTokenDto}
     * @memberof OAuth2ChallengeDto
     */
    tokens?: OAuth2ChallengeTokenDto | null;
}
