/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *   21999101 = TenantNotFound  21999102 = IntegrationNotFound  21999103 = UnknownExceptionWhenOAuth2Challenge  21999104 = IntegrationIsNotEnabled  21999105 = UnknownExceptionWhenCheckIfIntegrationIsEnabled  21999106 = UnknownExceptionWhenFetchTenant  21999107 = UnknownExceptionWhenTryToGetTenantTokens  21999108 = UnknownExceptionWhenReturnResponse  21999109 = UnknownExceptionWhenAddingTenantInKeycloak  21999110 = UnknownExceptionWhenAddingTenantInOrganization  21999111 = UnknownExceptionWhenTryToCreateTenantUser  21999112 = UnknownExceptionWhenTryToCheckIfTenantUserExists
 * @export
 * @enum {string}
 */
export enum OAuth2ChallengeErrorCodes {
    NUMBER_21999101 = 21999101,
    NUMBER_21999102 = 21999102,
    NUMBER_21999103 = 21999103,
    NUMBER_21999104 = 21999104,
    NUMBER_21999105 = 21999105,
    NUMBER_21999106 = 21999106,
    NUMBER_21999107 = 21999107,
    NUMBER_21999108 = 21999108,
    NUMBER_21999109 = 21999109,
    NUMBER_21999110 = 21999110,
    NUMBER_21999111 = 21999111,
    NUMBER_21999112 = 21999112
}

