/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RefreshAuthenticationTokenDto } from './refresh-authentication-token-dto';
import { RefreshAuthenticationTokenError } from './refresh-authentication-token-error';
 /**
 * 
 *
 * @export
 * @interface RefreshAuthenticationTokenResponse
 */
export interface RefreshAuthenticationTokenResponse {

    /**
     * @type {boolean}
     * @memberof RefreshAuthenticationTokenResponse
     */
    success?: boolean;

    /**
     * @type {RefreshAuthenticationTokenDto}
     * @memberof RefreshAuthenticationTokenResponse
     */
    data?: RefreshAuthenticationTokenDto | null;

    /**
     * @type {RefreshAuthenticationTokenError}
     * @memberof RefreshAuthenticationTokenResponse
     */
    error?: RefreshAuthenticationTokenError | null;
}
