/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Response
 */
export interface Response {

    /**
     * @type {any}
     * @memberof Response
     */
    data?: any | null;

    /**
     * @type {boolean}
     * @memberof Response
     */
    success?: boolean;

    /**
     * @type {Error}
     * @memberof Response
     */
    error?: Error | null;
}
