/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RevokeApplicationApiKeyError } from './revoke-application-api-key-error';
 /**
 * 
 *
 * @export
 * @interface RevokeApplicationApiKeyResponse
 */
export interface RevokeApplicationApiKeyResponse {

    /**
     * @type {any}
     * @memberof RevokeApplicationApiKeyResponse
     */
    data?: any | null;

    /**
     * @type {boolean}
     * @memberof RevokeApplicationApiKeyResponse
     */
    success?: boolean;

    /**
     * @type {RevokeApplicationApiKeyError}
     * @memberof RevokeApplicationApiKeyResponse
     */
    error?: RevokeApplicationApiKeyError | null;
}
