/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *   16998101 = ApplicationApiKeyNotFound  16998102 = UnknownExceptionWhenCheckApplicationExistence  16998103 = UnknownExceptionWhenGenerateApplicationApiKey
 * @export
 * @enum {string}
 */
export enum RevokeApplicationApiKeyRequestErrorCodes {
    NUMBER_16998101 = 16998101,
    NUMBER_16998102 = 16998102,
    NUMBER_16998103 = 16998103
}

