/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TenantDto } from './tenant-dto';
 /**
 * 
 *
 * @export
 * @interface TenantListDto
 */
export interface TenantListDto {

    /**
     * @type {Array<TenantDto>}
     * @memberof TenantListDto
     */
    dtos?: Array<TenantDto> | null;
}
