/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UpdateTenantConnectionRequest } from './update-tenant-connection-request';
import { UpdateTenantConnectionRequestDto } from './update-tenant-connection-request-dto';
 /**
 * 
 *
 * @export
 * @interface TenantUpdatetenantconnectionBody
 */
export interface TenantUpdatetenantconnectionBody extends UpdateTenantConnectionRequest {
}
