/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InviteTenantByApplicationIntegrationIdRequest } from './invite-tenant-by-application-integration-id-request';
import { InviteTenantByApplicationIntegrationIdRequestDto } from './invite-tenant-by-application-integration-id-request-dto';
 /**
 * 
 *
 * @export
 * @interface TenantInvitetenantbyapplicationintegrationidBody1
 */
export interface TenantInvitetenantbyapplicationintegrationidBody1 extends InviteTenantByApplicationIntegrationIdRequest {
}
