/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UnifiedContact } from './unified-contact';
 /**
 * 
 *
 * @export
 * @interface UnifiedContactResponse
 */
export interface UnifiedContactResponse {

    /**
     * @type {boolean}
     * @memberof UnifiedContactResponse
     */
    success?: boolean;

    /**
     * @type {UnifiedContact}
     * @memberof UnifiedContactResponse
     */
    data?: UnifiedContact | null;

    /**
     * @type {Error}
     * @memberof UnifiedContactResponse
     */
    error?: Error | null;
}
