/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *   15998101 = ApplicationNotFound  15998102 = UnknownExceptionWhenFetchApplication  15998103 = UnknownExceptionWhenInsertApplication
 * @export
 * @enum {string}
 */
export enum UpdateApplicationRequestErrorCodes {
    NUMBER_15998101 = 15998101,
    NUMBER_15998102 = 15998102,
    NUMBER_15998103 = 15998103
}

