/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateApplicationRequestDto
 */
export interface UpdateApplicationRequestDto {

    /**
     * @type {string}
     * @memberof UpdateApplicationRequestDto
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof UpdateApplicationRequestDto
     */
    description?: string | null;

    /**
     * @type {string}
     * @memberof UpdateApplicationRequestDto
     */
    category?: string | null;

    /**
     * @type {string}
     * @memberof UpdateApplicationRequestDto
     */
    officialLandingUrl?: string | null;

    /**
     * @type {string}
     * @memberof UpdateApplicationRequestDto
     */
    redirectBaseUrl?: string | null;

    /**
     * @type {string}
     * @memberof UpdateApplicationRequestDto
     */
    privacyPolicyUrl?: string | null;

    /**
     * @type {string}
     * @memberof UpdateApplicationRequestDto
     */
    endUserLicenseAgreementUrl?: string | null;

    /**
     * @type {string}
     * @memberof UpdateApplicationRequestDto
     */
    id?: string;
}
