/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *   20997101 = TenantNotFound  20997102 = UnknownExceptionWhenCheckTenantExistence  20997103 = UnknownExceptionWhenUpdateTenantConnection
 * @export
 * @enum {string}
 */
export enum UpdateTenantConnectionRequestErrorCodes {
    NUMBER_20997101 = 20997101,
    NUMBER_20997102 = 20997102,
    NUMBER_20997103 = 20997103
}

