/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UpdateTenantConnectionError } from './update-tenant-connection-error';
 /**
 * 
 *
 * @export
 * @interface UpdateTenantConnectionResponse
 */
export interface UpdateTenantConnectionResponse {

    /**
     * @type {any}
     * @memberof UpdateTenantConnectionResponse
     */
    data?: any | null;

    /**
     * @type {boolean}
     * @memberof UpdateTenantConnectionResponse
     */
    success?: boolean;

    /**
     * @type {UpdateTenantConnectionError}
     * @memberof UpdateTenantConnectionResponse
     */
    error?: UpdateTenantConnectionError | null;
}
