/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UpdateApplicationRequestDto } from './update-application-request-dto';
 /**
 * 
 *
 * @export
 * @interface UpdateApplicationRequest
 */
export interface UpdateApplicationRequest {

    /**
     * @type {UpdateApplicationRequestDto}
     * @memberof UpdateApplicationRequest
     */
    dto?: UpdateApplicationRequestDto | null;
}
