/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateTenantConnectionRequestDto
 */
export interface UpdateTenantConnectionRequestDto {

    /**
     * @type {string}
     * @memberof UpdateTenantConnectionRequestDto
     */
    tenantId?: string;

    /**
     * @type {string}
     * @memberof UpdateTenantConnectionRequestDto
     */
    clientId?: string | null;

    /**
     * @type {string}
     * @memberof UpdateTenantConnectionRequestDto
     */
    clientSecret?: string | null;

    /**
     * @type {string}
     * @memberof UpdateTenantConnectionRequestDto
     */
    scope?: string | null;
}
