/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *   20999101 = UnknownExceptionWhenTryingFetchTenants  20999102 = UserNotFound  20999103 = UnknownExceptionWhenInsertApplication
 * @export
 * @enum {string}
 */
export enum UserTenantListRequestErrorCodes {
    NUMBER_20999101 = 20999101,
    NUMBER_20999102 = 20999102,
    NUMBER_20999103 = 20999103
}

