/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *   15996101 = UnknownExceptionWhenTryingFetchApplications  15996102 = UserNotFound  15996103 = UnknownExceptionWhenInsertApplication
 * @export
 * @enum {string}
 */
export enum UserApplicationListRequestErrorCodes {
    NUMBER_15996101 = 15996101,
    NUMBER_15996102 = 15996102,
    NUMBER_15996103 = 15996103
}

