/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UserProfileStatisticsDto
 */
export interface UserProfileStatisticsDto {

    /**
     * @type {number}
     * @memberof UserProfileStatisticsDto
     */
    availableIntegrations?: number;

    /**
     * @type {number}
     * @memberof UserProfileStatisticsDto
     */
    availableApiCalls?: number;

    /**
     * @type {number}
     * @memberof UserProfileStatisticsDto
     */
    applicationsCount?: number;
}
