/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UserDto
 */
export interface UserDto {

    /**
     * @type {string}
     * @memberof UserDto
     */
    email?: string | null;

    /**
     * @type {string}
     * @memberof UserDto
     */
    phone?: string | null;

    /**
     * @type {string}
     * @memberof UserDto
     */
    username?: string | null;

    /**
     * @type {string}
     * @memberof UserDto
     */
    firstname?: string | null;

    /**
     * @type {string}
     * @memberof UserDto
     */
    lastname?: string | null;

    /**
     * @type {string}
     * @memberof UserDto
     */
    id?: string;
}
