/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ApplicationListDto } from './application-list-dto';
import { UserApplicationListError } from './user-application-list-error';
 /**
 * 
 *
 * @export
 * @interface UserApplicationListResponse
 */
export interface UserApplicationListResponse {

    /**
     * @type {boolean}
     * @memberof UserApplicationListResponse
     */
    success?: boolean;

    /**
     * @type {ApplicationListDto}
     * @memberof UserApplicationListResponse
     */
    data?: ApplicationListDto | null;

    /**
     * @type {UserApplicationListError}
     * @memberof UserApplicationListResponse
     */
    error?: UserApplicationListError | null;
}
