/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TenantListDto } from './tenant-list-dto';
import { UserTenantListError } from './user-tenant-list-error';
 /**
 * 
 *
 * @export
 * @interface UserTenantListResponse
 */
export interface UserTenantListResponse {

    /**
     * @type {boolean}
     * @memberof UserTenantListResponse
     */
    success?: boolean;

    /**
     * @type {TenantListDto}
     * @memberof UserTenantListResponse
     */
    data?: TenantListDto | null;

    /**
     * @type {UserTenantListError}
     * @memberof UserTenantListResponse
     */
    error?: UserTenantListError | null;
}
