/* tslint:disable */
/* eslint-disable */
/**
 * Terapi.Web.Api-v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *   14997101 = UserNotFound  14997102 = UserDoesNotHaveActiveSubscription  14997103 = UnknownExceptionWhenFetchUserProfileStatistics
 * @export
 * @enum {string}
 */
export enum UserProfileStatisticsErrorCodes {
    NUMBER_14997101 = 14997101,
    NUMBER_14997102 = 14997102,
    NUMBER_14997103 = 14997103
}

